import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center min-h-dvh text-sm transition-colors duration-300 text-neutral-600 focus:outline-none focus:ring focus:ring-neutral-500 bg-neutral-100 dark:text-neutral-300 dark:bg-neutral-900">
        <Header />
        <main className="h-full mt-14 container max-w-screen-sm px-6 pt-[72px] pb-12">
          {children}
        </main>
      </body>
    </html>
  );
}
